services:
  postgres:
    container_name: standard-pipelines_postgres
    image: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - standard-pipelines_postgres_data:/var/lib/postgresql/data

  adminer:
    container_name: standard-pipelines_adminer
    image: adminer
    ports:
      - 8080:8080

volumes:
  standard-pipelines_postgres_data: