version: "3.8"

x-production-secrets: &production-secrets
  secrets:
    - standard_pipelines_production_db_name
    - standard_pipelines_production_db_pass
    - standard_pipelines_production_db_user
    - standard_pipelines_production_encryption_key
    - standard_pipelines_production_security_password_salt
    - standard_pipelines_production_secret_key
    - standard_pipelines_production_default_admin_account
    - standard_pipelines_production_default_admin_password
    - standard_pipelines_production_mailgun_api_key
    - standard_pipelines_production_mailgun_send_domain
    - standard_pipelines_production_sentry_dsn
    - standard_pipelines_production_openai_api_key
    - standard_pipelines_production_internal_api_key
    - standard_pipelines_production_bitwarden_organization_id
    - standard_pipelines_production_bitwarden_access_token
    - standard_pipelines_production_hubspot_client_id
    - standard_pipelines_production_hubspot_client_secret
    - standard_pipelines_production_zoho_client_id
    - standard_pipelines_production_zoho_client_secret
    - standard_pipelines_production_google_client_id
    - standard_pipelines_production_google_client_secret
    - standard_pipelines_production_papertrail_host
    - standard_pipelines_production_papertrail_port
    - standard_pipelines_production_papertrail_system_hostname

x-base-service: &base-service
# TODO: REMEMBER TO CHANGE MIGRATIONS
  image: ghcr.io/agentic-brain/standard_pipelines:v0.0.12
  # secrets:
    # - github-token
  environment:
    - FLASK_ENV=production
    - PRODUCTION_DB_HOST=standard_pipelines_production_postgres
    - PRODUCTION_DB_PORT=5432
    - PRODUCTION_BITWARDEN_STATE_FILE_PATH=/bitwarden-state
    - PRODUCTION_DEFAULT_CLIENT_BITWARDEN_KEY_ID=b5e69235-8670-4b89-9135-b26b017f5906
    - PRODUCTION_MAILGUN_SEND_USER=noreply@agenticbrain.com
    - PRODUCTION_REDIS_HOST=standard_pipelines_production_redis
    - PRODUCTION_GOOGLE_REDIRECT_URI=https://agents.agentic-internal.com/api/google/oauth/authorize
    - PRODUCTION_GOOGLE_SCOPES=https://www.googleapis.com/auth/gmail.modify https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
    - PRODUCTION_FLASK_APP=standard_pipelines
    - PRODUCTION_ENABLE_PAPERTRAIL_LOGGING=True
  <<: *production-secrets

services:
  standard_pipelines:
    <<: *base-service
    ports:
      - 5050:5000
    depends_on:
      - postgres
      - adminer
      - migrations
      - redis

  celery_worker:
    <<: *base-service
    command: uv run celery -A standard_pipelines.make_celery worker --loglevel=info --pool=solo
    depends_on:
      - postgres
      - redis

  celery_beat:
    <<: *base-service
    command: uv run celery -A standard_pipelines.make_celery beat --loglevel=info
    depends_on:
      - postgres
      - redis

  migrations:
    <<: *base-service
    command: /bin/sh -c "uv run flask db upgrade && uv run flask create-default-admin && uv run flask init-flows"
    environment:
      - PRODUCTION_ENABLE_PAPERTRAIL_LOGGING=False
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_DB_FILE: /run/secrets/standard_pipelines_production_db_name
      POSTGRES_PASSWORD_FILE: /run/secrets/standard_pipelines_production_db_pass
      POSTGRES_USER_FILE: /run/secrets/standard_pipelines_production_db_user
    volumes:
      - standard_pipelines_postgres_data_production:/var/lib/postgresql/data
    secrets:
      - standard_pipelines_production_db_name
      - standard_pipelines_production_db_pass
      - standard_pipelines_production_db_user

  adminer:
    image: adminer
    ports:
      - 8050:8080

  redis:
    image: redis:latest
    container_name: standard_pipelines_redis_production
    volumes:
      - standard_pipelines_redis_data_production:/data

volumes:
  standard_pipelines_postgres_data_production:
  standard_pipelines_redis_data_production:
secrets:
  standard_pipelines_production_db_name:
    external: true
  standard_pipelines_production_db_pass:
    external: true
  standard_pipelines_production_db_user:
    external: true
  standard_pipelines_production_encryption_key:
    external: true
  standard_pipelines_production_security_password_salt:
    external: true
  standard_pipelines_production_secret_key:
    external: true
  standard_pipelines_production_default_admin_account:
    external: true
  standard_pipelines_production_default_admin_password:
    external: true
  # github-token:
    # external: true 
  standard_pipelines_production_mailgun_api_key:
    external: true
  standard_pipelines_production_mailgun_send_domain:
    external: true
  standard_pipelines_production_sentry_dsn:
    external: true
  standard_pipelines_production_openai_api_key:
    external: true
  standard_pipelines_production_internal_api_key:
    external: true
  standard_pipelines_production_bitwarden_access_token:
    external: true
  standard_pipelines_production_bitwarden_organization_id:
    external: true
  standard_pipelines_production_hubspot_client_id:
    external: true
  standard_pipelines_production_hubspot_client_secret:
    external: true
  standard_pipelines_production_zoho_client_id:
    external: true
  standard_pipelines_production_zoho_client_secret:
    external: true
  standard_pipelines_production_google_client_id:
    external: true
  standard_pipelines_production_google_client_secret:
    external: true
  standard_pipelines_production_papertrail_host:
    external: true
  standard_pipelines_production_papertrail_port:
    external: true
  standard_pipelines_production_papertrail_system_hostname:
    external: true