version: "3.8"

x-staging-secrets: &staging-secrets
  secrets:
    - standard_pipelines_staging_db_name
    - standard_pipelines_staging_db_pass
    - standard_pipelines_staging_db_user
    - standard_pipelines_staging_encryption_key
    - standard_pipelines_staging_security_password_salt
    - standard_pipelines_staging_secret_key
    - standard_pipelines_staging_default_admin_account
    - standard_pipelines_staging_default_admin_password
    - standard_pipelines_staging_mailgun_api_key
    - standard_pipelines_staging_mailgun_send_domain
    - standard_pipelines_staging_sentry_dsn
    - standard_pipelines_staging_openai_api_key
    - standard_pipelines_staging_internal_api_key
    - standard_pipelines_staging_bitwarden_access_token
    - standard_pipelines_staging_bitwarden_organization_id
    - standard_pipelines_staging_bitwarden_default_client_bitwarden_key_id
    - standard_pipelines_staging_hubspot_client_id
    - standard_pipelines_staging_hubspot_client_secret
    - standard_pipelines_staging_google_client_id
    - standard_pipelines_staging_google_client_secret
x-base-service: &base-service
  image: ghcr.io/agentic-brain/standard_pipelines:v0.0.0
  secrets:
    - github-token
  environment:
    - FLASK_ENV=staging
    - STAGING_DB_HOST=standard_pipelines_staging_postgres
    - STAGING_DB_PORT=5432
    - STAGING_REDIS_HOST=standard_pipelines_staging_redis
    - STAGING_BITWARDEN_STATE_FILE_PATH=/bitwarden-state
    - STAGING_DEFAULT_CLIENT_BITWARDEN_KEY_ID=b5e69235-8670-4b89-9135-b26b017f5906
    - STAGING_MAILGUN_SEND_USER=noreply@agenticbrain.com
    - STAGING_GOOGLE_REDIRECT_URI=https://staging.agenticbrain.com/api/auth/google/callback
  <<: *staging-secrets

services:
  standard_pipelines:
    <<: *base-service
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - adminer
      - migrations

  migrations:
    <<: *base-service
    command: /bin/sh -c "flask db upgrade && flask create-admin && flask init-flows"
    depends_on:
      - postgres
  
  celery_worker:
    <<: *base-service
    command: celery -A standard_pipelines.celery.worker worker --loglevel=info --pool=solo
    depends_on:
      - postgres
      - redis

  celery_beat:
    <<: *base-service
    command: celery -A standard_pipelines.celery.worker beat --loglevel=info
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    shm_size: 128mb
    environment:
      POSTGRES_DB_FILE: /run/secrets/standard_pipelines_staging_db_name
      POSTGRES_PASSWORD_FILE: /run/secrets/standard_pipelines_staging_db_pass
      POSTGRES_USER_FILE: /run/secrets/standard_pipelines_staging_db_user
    volumes:
      - standard_pipelines_postgres_data_staging:/var/lib/postgresql/data
    secrets:
      - standard_pipelines_staging_db_name
      - standard_pipelines_staging_db_pass
      - standard_pipelines_staging_db_user

  adminer:
    image: adminer
    ports:
      - 8080:8080
  redis:
    image: redis:latest
    container_name: standard_pipelines_redis_staging
    volumes:
      - standard_pipelines_redis_data_staging:/data

volumes:
  standard_pipelines_postgres_data_staging:
  standard_pipelines_redis_data_staging:

secrets:
  standard_pipelines_staging_db_name:
    external: true
  standard_pipelines_staging_db_pass:
    external: true
  standard_pipelines_staging_db_user:
    external: true
  standard_pipelines_staging_encryption_key:
    external: true
  standard_pipelines_staging_security_password_salt:
    external: true
  standard_pipelines_staging_secret_key:
    external: true
  standard_pipelines_staging_default_admin_account:
    external: true
  standard_pipelines_staging_default_admin_password:
    external: true
  github-token:
    external: true 
  standard_pipelines_staging_mailgun_api_key:
    external: true
  standard_pipelines_staging_mailgun_send_domain:
    external: true
  standard_pipelines_staging_sentry_dsn:
    external: true
  standard_pipelines_staging_openai_api_key:
    external: true
  standard_pipelines_staging_internal_api_key:
    external: true
  standard_pipelines_staging_bitwarden_access_token:
    external: true
  standard_pipelines_staging_bitwarden_state_file_path:
    external: true
  standard_pipelines_staging_bitwarden_organization_id:
    external: true
  standard_pipelines_staging_bitwarden_default_client_bitwarden_key_id:
    external: true
  standard_pipelines_staging_hubspot_client_id:
    external: true
  standard_pipelines_staging_hubspot_client_secret:
    external: true
  standard_pipelines_staging_google_client_id:
    external: true
  standard_pipelines_staging_google_client_secret:
    external: true
