"""Added dp2ss flow config

Revision ID: 0745874c816e
Revises: 3811deaa3e2f
Create Date: 2025-02-28 02:50:17.933939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0745874c816e'
down_revision = '3811deaa3e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dp2ss_on_transcript_configuration',
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('dp2ss_on_transcript_configuration', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_dp2ss_on_transcript_configuration', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_dp2ss_on_transcript_configuration', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dp2ss_on_transcript_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_dp2ss_on_transcript_configuration', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_dp2ss_on_transcript_configuration', postgresql_where=sa.text('client_id IS NULL'))

    op.drop_table('dp2ss_on_transcript_configuration')
    # ### end Alembic commands ###
