"""various migrations

Revision ID: 08877814fd90
Revises: 84826116fc11
Create Date: 2025-05-07 12:40:27.258079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08877814fd90'
down_revision = '84826116fc11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('append_hubspot_note_configuration',
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('append_hubspot_note_configuration', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_append_hubspot_note_configuration', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_append_hubspot_note_configuration', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    op.create_table('sharpspring_credential',
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('add_data_to_hubspot_field_configuration', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('dialpad2zoho_on_transcript_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followup_webhook_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('initial_deal_stage_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('lead_followup_human_notification_config', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_followup_human_notification_config', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('dialpad2zoho_on_transcript_configuration', schema=None) as batch_op:
        batch_op.alter_column('initial_deal_stage_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('followup_webhook_url')

    with op.batch_alter_table('add_data_to_hubspot_field_configuration', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.UUID(),
               nullable=False)

    op.drop_table('sharpspring_credential')
    with op.batch_alter_table('append_hubspot_note_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_append_hubspot_note_configuration', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_append_hubspot_note_configuration', postgresql_where=sa.text('client_id IS NULL'))

    op.drop_table('append_hubspot_note_configuration')
    # ### end Alembic commands ###
