"""add initial hubspot deal stage id

Revision ID: 1d2576cbefd5
Revises: c2a0f8cf754a
Create Date: 2025-02-05 13:10:00.085620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2576cbefd5'
down_revision = 'c2a0f8cf754a'
branch_labels = None
depends_on = None


def upgrade():
    """Create a new column for the initial deal stage id and fill it with the value 'contractsent'."""

    with op.batch_alter_table("ff2hs_on_transcript_configuration", schema=None) as batch_op:
        batch_op.add_column(sa.Column("initial_deal_stage_id", sa.String(length=255), nullable=True))
    op.execute("UPDATE ff2hs_on_transcript_configuration SET initial_deal_stage_id = 'contractsent'")
    with op.batch_alter_table("ff2hs_on_transcript_configuration", schema=None) as batch_op:
        batch_op.alter_column(
            "initial_deal_stage_id",
            existing_type=sa.String(length=255),
            nullable=False
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.drop_column('initial_deal_stage_id')

    # ### end Alembic commands ###
