"""add initial hubspot deal stage id

Revision ID: 1d2576cbefd5
Revises: c2a0f8cf754a
Create Date: 2025-02-05 13:10:00.085620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d2576cbefd5'
down_revision = 'c2a0f8cf754a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intial_deal_stage_id', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.drop_column('intial_deal_stage_id')

    # ### end Alembic commands ###
