"""added email and name to google credentials

Revision ID: 275cf7fc677b
Revises: d43d82df0af8
Create Date: 2025-02-13 23:42:30.555719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275cf7fc677b'
down_revision = 'd43d82df0af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
