"""Add ZohoCredentials table

Revision ID: 45a7ba2d18ad
Revises: d2dc21fd386e
Create Date: 2025-02-27 21:05:57.949239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a7ba2d18ad'
down_revision = 'd2dc21fd386e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoho_credential',
    sa.Column('zoho_client_id', sa.String(length=255), nullable=False),
    sa.Column('zoho_client_secret', sa.String(length=255), nullable=False),
    sa.Column('zoho_refresh_token', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('zoho_credential')
    # ### end Alembic commands ###
