"""add microsoft oauth table

Revision ID: 4c9a4547807b
Revises: 1e0e46312268
Create Date: 2025-03-07 16:23:00.972625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9a4547807b'
down_revision = '1e0e46312268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microsoft_credential',
    sa.Column('access_token', sa.String(length=4000), nullable=False),
    sa.Column('refresh_token', sa.String(length=4000), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=511), nullable=False),
    sa.Column('user_name', sa.String(length=511), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('microsoft_credential')
    # ### end Alembic commands ###
