"""add microsoft oauth table

Revision ID: 5a51795f2384
Revises: 714fe394a0ab
Create Date: 2025-03-07 14:24:37.917698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a51795f2384'
down_revision = '714fe394a0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('microsoft_credential',
    sa.Column('access_token', sa.String(length=4000), nullable=False),
    sa.Column('refresh_token', sa.String(length=4000), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=511), nullable=False),
    sa.Column('user_name', sa.String(length=511), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('microsoft_credential')
    # ### end Alembic commands ###
