"""Added Dialpad credentials

Revision ID: 652566ec6952
Revises: f20d6ec2c228
Create Date: 2025-02-19 15:41:43.720920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '652566ec6952'
down_revision = 'f20d6ec2c228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialpad_credential',
    sa.Column('dialpad_api_key', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialpad_credential')
    # ### end Alembic commands ###
