"""index fix

Revision ID: 6cb362c4fd38
Revises: 9f69953c47f3
Create Date: 2025-02-20 02:31:39.081184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cb362c4fd38'
down_revision = '9f69953c47f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_ff2hs_on_transcript_configuration', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_ff2hs_on_transcript_configuration', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    with op.batch_alter_table('gmail_interval_followup_configuration', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_gmail_interval_followup_configuration', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_gmail_interval_followup_configuration', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    with op.batch_alter_table('gmail_interval_followup_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmail_interval_followup_schedule_next_poll_time'), ['next_poll_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_gmail_interval_followup_schedule_scheduled_time'), ['scheduled_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_interval_followup_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmail_interval_followup_schedule_scheduled_time'))
        batch_op.drop_index(batch_op.f('ix_gmail_interval_followup_schedule_next_poll_time'))

    with op.batch_alter_table('gmail_interval_followup_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_gmail_interval_followup_configuration', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_gmail_interval_followup_configuration', postgresql_where=sa.text('client_id IS NULL'))

    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_ff2hs_on_transcript_configuration', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_ff2hs_on_transcript_configuration', postgresql_where=sa.text('client_id IS NULL'))

    # ### end Alembic commands ###
