"""Added Dialpad credentials

Revision ID: 714fe394a0ab
Revises: d2dc21fd386e
Create Date: 2025-02-21 16:17:28.088228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714fe394a0ab'
down_revision = 'd2dc21fd386e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialpad_credential',
    sa.Column('dialpad_api_key', sa.String(length=255), nullable=False),
    sa.Column('dialpad_jwt_secret', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dialpad_credential')
    # ### end Alembic commands ###
