"""gmail followup configs

Revision ID: 7233eb5802e4
Revises: 558cea3f51fe
Create Date: 2025-02-19 01:26:21.499125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7233eb5802e4'
down_revision = '558cea3f51fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_interval_followup_configuration',
    sa.Column('email_interval_days', sa.Integer(), nullable=False),
    sa.Column('email_retries', sa.Integer(), nullable=False),
    sa.Column('email_body_prompt', sa.Text(), nullable=False),
    sa.Column('subject_line_template', sa.Text(), nullable=False),
    sa.Column('internal_domain', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )


    op.create_table('gmail_interval_followup_schedule',
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_credentials_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('active_hours', sa.JSON(), nullable=True),
    sa.Column('active_days', sa.JSON(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['gmail_interval_followup_configuration.id'], ),
    sa.ForeignKeyConstraint(['gmail_credentials_id'], ['google_credential.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gmail_interval_followup_schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gmail_interval_followup_schedule_scheduled_time'), ['scheduled_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_interval_followup_schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gmail_interval_followup_schedule_scheduled_time'))

    op.drop_table('gmail_interval_followup_schedule')
    with op.batch_alter_table('gmail_interval_followup_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_config', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_config', postgresql_where=sa.text('client_id IS NULL'))

    op.drop_table('gmail_interval_followup_configuration')
    # ### end Alembic commands ###
