"""followup human notif

Revision ID: 84826116fc11
Revises: 1e0e46312268
Create Date: 2025-04-14 14:04:31.375354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84826116fc11'
down_revision = '1e0e46312268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_data_to_hubspot_field_configuration',
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('add_data_to_hubspot_field_configuration', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_add_data_to_hubspot_field_configuration', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_add_data_to_hubspot_field_configuration', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    op.create_table('lead_followup_human_notification_config',
    sa.Column('fallback_destination_email', sa.String(length=255), nullable=False),
    sa.Column('cc_addresses', sa.JSON(), nullable=True),
    sa.Column('source_email', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('lead_followup_human_notification_config', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_lead_followup_human_notification_config', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_lead_followup_human_notification_config', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lead_followup_human_notification_config', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_lead_followup_human_notification_config', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_lead_followup_human_notification_config', postgresql_where=sa.text('client_id IS NULL'))

    op.drop_table('lead_followup_human_notification_config')
    with op.batch_alter_table('add_data_to_hubspot_field_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_add_data_to_hubspot_field_configuration', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_add_data_to_hubspot_field_configuration', postgresql_where=sa.text('client_id IS NULL'))

    op.drop_table('add_data_to_hubspot_field_configuration')
    # ### end Alembic commands ###
