"""added openai credentials

Revision ID: 98820cd10142
Revises: 95a1e04e3195
Create Date: 2025-01-27 23:56:31.368786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98820cd10142'
down_revision = '95a1e04e3195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openai_credential',
    sa.Column('openai_api_key', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openai_credential')
    # ### end Alembic commands ###
