"""gmail interval schedule config

Revision ID: 9f69953c47f3
Revises: f20d6ec2c228
Create Date: 2025-02-20 01:26:45.283439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f69953c47f3'
down_revision = 'f20d6ec2c228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_interval_followup_configuration',
    sa.Column('email_interval_days', sa.Integer(), server_default='10080', nullable=False),
    sa.Column('email_retries', sa.Integer(), server_default='5', nullable=False),
    sa.Column('email_body_prompt', sa.Text(), nullable=False),
    sa.Column('followup_body_prompt', sa.Text(), nullable=False),
    sa.Column('subject_line_template', sa.Text(), nullable=False),
    sa.Column('internal_domain', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    

    op.create_table('gmail_interval_followup_schedule',
    sa.Column('configuration_id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('gmail_credentials_id', sa.UUID(), nullable=False),
    sa.Column('original_transcript', sa.Text(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('active_hours', sa.JSON(), nullable=True),
    sa.Column('active_days', sa.JSON(), nullable=True),
    sa.Column('recurrence_interval', sa.Integer(), nullable=True),
    sa.Column('poll_interval', sa.Integer(), nullable=True),
    sa.Column('next_poll_time', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['configuration_id'], ['gmail_interval_followup_configuration.id'], ),
    sa.ForeignKeyConstraint(['gmail_credentials_id'], ['google_credential.id'], ),
    sa.PrimaryKeyConstraint('id')
    )


    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.drop_column('user_name')
        batch_op.drop_column('user_email')


    op.drop_table('gmail_interval_followup_schedule')


    op.drop_table('gmail_interval_followup_configuration')
    # ### end Alembic commands ###
