"""increased openai api key length

Revision ID: a9c4adc80188
Revises: 7e5289365d67
Create Date: 2025-01-30 19:41:59.304616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c4adc80188'
down_revision = '7e5289365d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openai_credential', schema=None) as batch_op:
        batch_op.alter_column('openai_api_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('openai_credential', schema=None) as batch_op:
        batch_op.alter_column('openai_api_key',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
