"""Add Notion OAuth credentials table

Revision ID: aeeabd940510
Revises: 92c480da6c1d
Create Date: 2025-05-28 20:05:05.703905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeeabd940510'
down_revision = '92c480da6c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notion_credential',
    sa.Column('bot_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_id', sa.String(length=255), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('workspace_icon', sa.String(length=512), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('owner_user_id', sa.String(length=255), nullable=True),
    sa.Column('owner_user_name', sa.String(length=255), nullable=True),
    sa.Column('owner_user_email', sa.String(length=255), nullable=True),
    sa.Column('oauth_refresh_token', sa.String(length=512), nullable=False),
    sa.Column('oauth_access_token', sa.String(length=512), nullable=True),
    sa.Column('oauth_token_expires_at', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notion_credential')
    # ### end Alembic commands ###
