"""fireflies2zoho_on_transcript_configuration

Revision ID: c5c56465fe58
Revises: 5164608501b3
Create Date: 2025-03-04 18:56:54.453060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c56465fe58'
down_revision = '5164608501b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fireflies2zoho_on_transcript_configuration',
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('initial_deal_stage_id', sa.String(length=255), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('fireflies2zoho_on_transcript_configuration', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_fireflies2zoho_on_transcript_configuration', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_fireflies2zoho_on_transcript_configuration', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    with op.batch_alter_table('zoho_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('oauth_expires_at',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('zoho_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_expires_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('fireflies2zoho_on_transcript_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_fireflies2zoho_on_transcript_configuration', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_fireflies2zoho_on_transcript_configuration', postgresql_where=sa.text('client_id IS NULL'))

    op.drop_table('fireflies2zoho_on_transcript_configuration')
    # ### end Alembic commands ###
