"""removed constraint on google creds

Revision ID: d2dc21fd386e
Revises: 6cb362c4fd38
Create Date: 2025-02-23 23:14:16.686945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2dc21fd386e'
down_revision = '6cb362c4fd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.drop_constraint('google_credential_client_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.create_unique_constraint('google_credential_client_id_key', ['client_id'])

    # ### end Alembic commands ###
