"""ff2hs

Revision ID: f1cc8115ebcc
Revises: 07bc275c623c
Create Date: 2025-01-23 21:15:03.496499

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f1cc8115ebcc'
down_revision = '07bc275c623c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('data_flow_registry',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('client_data_flow_registry_join',
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('webhook_id', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('data_flow_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_flow_id'], ['data_flow_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ff2hs_on_transcript_configuration',
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registry_id'], ['data_flow_registry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.create_index('ix_unique_client_id_config', ['registry_id', 'client_id'], unique=True, postgresql_where=sa.text('client_id IS NULL'))
        batch_op.create_index('ix_unique_default_config', ['registry_id', 'is_default'], unique=True, postgresql_where=sa.text('is_default = true'))

    op.drop_table('contacts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uri', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_role_join', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_role_join', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_column('modified_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('uri')

    op.create_table('contacts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('hubspot_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contacts_pkey'),
    sa.UniqueConstraint('hubspot_id', name='contacts_hubspot_id_key')
    )
    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_config', postgresql_where=sa.text('is_default = true'))
        batch_op.drop_index('ix_unique_client_id_config', postgresql_where=sa.text('client_id IS NULL'))

    op.drop_table('ff2hs_on_transcript_configuration')
    op.drop_table('client_data_flow_registry_join')
    op.drop_table('data_flow_registry')
    op.drop_table('client')
    # ### end Alembic commands ###
