"""email domain

Revision ID: f20d6ec2c228
Revises: d43d82df0af8
Create Date: 2025-02-18 20:55:08.731621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20d6ec2c228'
down_revision = 'd43d82df0af8'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table("ff2hs_on_transcript_configuration", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email_domain", sa.String(length=255), nullable=True))
    op.execute("UPDATE ff2hs_on_transcript_configuration SET email_domain = 'placeholder'")
    with op.batch_alter_table("ff2hs_on_transcript_configuration", schema=None) as batch_op:
        batch_op.alter_column(
            "email_domain",
            existing_type=sa.String(length=255),
            nullable=False
        )

    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.alter_column('refresh_token',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('ff2hs_on_transcript_configuration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('initial_deal_stage_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('email_domain')

    # ### end Alembic commands ###
