"""Create gmail_credential table

Revision ID: f2b8a690e006
Revises: 98820cd10142
Create Date: 2025-01-28 18:41:52.615949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b8a690e006'
down_revision = '98820cd10142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_credential',
    sa.Column('access_token', sa.String(length=512), nullable=False),
    sa.Column('expire_time', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=512), nullable=False),
    sa.Column('token_uri', sa.String(length=255), nullable=False),
    sa.Column('oauth_client_id', sa.String(length=255), nullable=False),
    sa.Column('oauth_client_secret', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gmail_credential')
    # ### end Alembic commands ###
