"""changed to text

Revision ID: f57e6dc3a6ad
Revises: dc750294cad7
Create Date: 2025-05-29 12:39:37.185513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f57e6dc3a6ad'
down_revision = 'dc750294cad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('hubspot_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('notion_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('office365_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('office365_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('notion_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('hubspot_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    with op.batch_alter_table('google_credential', schema=None) as batch_op:
        batch_op.alter_column('oauth_access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=True)
        batch_op.alter_column('oauth_refresh_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###
