"""
Notion API routes.

OAuth routes are automatically generated by the OAuth system.
This file is for any additional Notion-specific API endpoints.
"""
from flask import jsonify, current_app
from flask_login import login_required, current_user
from standard_pipelines.api import api
from standard_pipelines.api.notion.models import NotionCredentials


@api.route('/notion/workspaces')
@login_required
def get_notion_workspaces():
    """Get all connected Notion workspaces for the current user's client."""
    try:
        credentials = NotionCredentials.query.filter_by(
            client_id=current_user.client_id
        ).all()
        
        workspaces = []
        for cred in credentials:
            workspaces.append({
                'workspace_id': cred.workspace_id,
                'workspace_name': cred.workspace_name,
                'workspace_icon': cred.workspace_icon,
                'bot_id': cred.bot_id,
                'owner_type': cred.owner_type,
                'owner_name': cred.owner_user_name or 'Workspace'
            })
        
        return jsonify({
            'success': True,
            'workspaces': workspaces,
            'count': len(workspaces)
        })
        
    except Exception as e:
        current_app.logger.error(f"Error fetching Notion workspaces: {e}")
        return jsonify({
            'success': False,
            'error': 'Failed to fetch workspaces'
        }), 500