name: Build and Publish Docker Image

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  build-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Run Unit Tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Get BWS Secrets
        uses: bitwarden/sm-action@v1
        with:
          access_token: ${{ secrets.BWS_ACCESS_TOKEN }}
          secrets: |
            "organization/${{ secrets.BWS_PROJECT_ID }}" |
            DOCKER_USERNAME => DOCKER_USERNAME;
            DOCKER_PASSWORD => DOCKER_PASSWORD;
            DOCKER_REGISTRY => DOCKER_REGISTRY;

      - name: Build Docker Image
        run: |
          COMMIT_HASH=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
          docker build -t ${{ env.DOCKER_REGISTRY }}/standard-pipelines:${COMMIT_HASH} .

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          COMMIT_HASH=$(echo "${{ github.event.pull_request.head.sha }}" | cut -c1-7)
          docker push ${{ env.DOCKER_REGISTRY }}/standard-pipelines:${COMMIT_HASH}
