name: Run Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv sync
        uv pip install pytest pytest-cov

    - name: Install Bitwarden Secrets CLI
      run: |
        curl -L --output bws.zip "https://github.com/bitwarden/sdk/releases/download/bws-v0.3.0/bws-x86_64-unknown-linux-gnu-0.3.0.zip"
        unzip bws.zip
        chmod +x bws
        sudo mv bws /usr/local/bin/bws
        rm bws.zip

    - name: Pull Secrets
      env:
        BWS_ACCESS_TOKEN: ${{ secrets.TESTING_BWS_ACCESS_TOKEN }}
      run: |
        chmod +x .github/scripts/pull_secrets.sh
        .github/scripts/pull_secrets.sh "testing_keys" "testing" --github-env

    - name: Set test environment variables
      run: |
        echo "FLASK_ENV=testing" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        pytest --cov=standard_pipelines --cov-report=term-missing

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: .coverage
        
